FROM ruby:2.3.3

RUN apt-get install git curl
RUN gem install sinatra --no-rdoc --no-ri
RUN curl -sL https://deb.nodesource.com/setup_7.x | bash
RUN apt-get install nodejs

COPY ["Gemfile", "/Gemfile"]
COPY ["lint.sh", "/lint.sh"]
COPY ["lint.rb", "/lint.rb"]
COPY ["unit.rb", "/unit.rb"]

ENTRYPOINT ["/lint.sh"]
EXPOSE 4000
