FROM ruby:2.3.3

RUN apt-get install git curl
RUN gem install sinatra --no-rdoc --no-ri
RUN curl -sL https://deb.nodesource.com/setup_7.x | bash
RUN apt-get install nodejs

RUN mkdir proj && cd proj && git clone https://github.com/ApoorvSaxena/lozad.js.git && cd * && npm install

COPY ["Gemfile", "/Gemfile"]
COPY ["unit.sh", "/unit.sh"]
COPY ["lint.rb", "/lint.rb"]
COPY ["unit.rb", "/unit.rb"]

ENTRYPOINT ["/unit.sh"]
EXPOSE 4001
